LONG_DICT={
    'Full':
    {
        'unload_red_traybox': 'unload the ball into the red traybox', 
        'unload_green_traybox': 'unload the ball into the green traybox', 
        'unload_yellow_traybox': 'unload the ball into the yellow traybox', 
        'unload_blue_traybox': 'unload the ball into the blue traybox', 
    }
}


SIM_INSTRUCTION_DICT = {
    '1228_test':
    {
        'go_to_purple_cube': 'go to the purple cube', 
    },
    '0116_test': 
    {
        'go_to_texture_vase': 'go to the vase', 
        'go_to_orange_ball': 'go to the orange ball', 
        'go_to_texture_fan': 'go to the fan', 
        'go_to_texture_bookshelf': 'go to the bookshelf', 
        'go_avoid_texture_drawers': 'go to the drawers and avoid the obstacle', 
        'go_avoid_texture_fence': 'go to the fence and avoid the obstacle', 
        'go_to_texture_bench': 'go to the bench', 
        'go_avoid_texture_trashcan': 'go to the trashcan and avoid the obstacle', 
        'go_avoid_texture_bookshelf': 'go to the bookshelf and avoid the obstacle', 
        'go_avoid_texture_oven': 'go to the oven and avoid the obstacle',
        'go_avoid_red_cube': 'go to the red cube and avoid the obstacle', 
        'go_to_purple_cube': 'go to the purple cube', 
        'go_avoid_tan_ball': 'go to the tan ball and avoid the obstacle', 
        'go_to_texture_wardrobe': 'go to the wardrobe', 
        'go_avoid_texture_sofa': 'go to the sofa and avoid the obstacle',
        'go_avoid_orange_cube': 'go to the orange cube and avoid the obstacle', 
        'go_to_texture_cooker': 'go to the cooker', 
        'go_avoid_purple_ball': 'go to the purple ball and avoid the obstacle', 
        'go_to_texture_trashcan': 'go to the trashcan',
        'go_avoid_texture_wardrobe': 'go to the wardrobe and avoid the obstacle', 
        'go_avoid_texture_barrel': 'go to the barrel and avoid the obstacle', 
        'go_avoid_texture_fan': 'go to the fan and avoid the obstacle',
        'go_to_texture_fence': 'go to the fence', 
        'go_to_texture_piano': 'go to the piano', 
        'go_avoid_texture_table': 'go to the table and avoid the obstacle',
        'go_avoid_texture_piano': 'go to the piano and avoid the obstacle', 
        'go_avoid_texture_vase': 'go to the vase and avoid the obstacle', 
        'go_to_texture_drawers': 'go to the drawers', 
        'go_avoid_texture_cooker': 'go to the cooker and avoid the obstacle', 
        'go_to_texture_barrel': 'go to the barrel', 
        'go_to_texture_chair': 'go to the chair', 
        'go_to_texture_table': 'go to the table', 
        'go_avoid_texture_chair': 'go to the chair and avoid the obstacle', 
        'go_to_texture_sofa': 'go to the sofa', 
        'go_avoid_texture_bench': 'go to the bench and avoid the obstacle', 
        'go_to_texture_oven': 'go to the oven', 
        'go_avoid_green_ball': 'go to the green ball and avoid the obstacle', 
        'go_avoid_green_cube': 'go to the green cube and avoid the obstacle', 
        'go_avoid_blue_cube': 'go to the blue cube and avoid the obstacle', 
        'go_to_cyan_cube': 'go to the cyan cube', 
        'go_to_gold_cube': 'go to the gold cube', 
        'go_avoid_cyan_ball': 'go to the cyan ball and avoid the obstacle', 
        'go_through_pink_triangle tunnel': 'go through the pink triangle tunnel', 
        'go_avoid_pink_ball': 'go to the pink ball and avoid the obstacle', 
        'go_avoid_navy_ball': 'go to the navy ball and avoid obstacle',
        'go_to_silver_ball': 'go to the silver ball', 
        'go_to_black_ball': 'go to the black ball', 
        'go_to_red_cube': 'go to the red cube', 
        'go_avoid_black_ball': 'go to the black ball and avoid the obstacle', 
        'go_avoid_yellow_cube': 'go to the yellow cube and avoid the obstacle', 
        'go_to_white_cube': 'go to the white cube',
        'go_avoid_white_cube': 'go to the white cube and avoid the obstacle', 
        'go_avoid_cyan_cube': 'go to the cyan cube and avoid the obstacle', 
        'go_avoid_gray_cube': 'go to the gray cube and avoid the obstacle', 
        'go_avoid_purple_cube': 'go to the purple cube and avoid the obstacle', 
        'go_to_navy_ball': 'go to the navy ball', 
        'go_to_tan_cube': 'go to the tan cube', 
        'go_to_pink_ball': 'go to the pink ball', 
        'go_avoid_beige_ball': 'go to the beige ball and avoid the obstacle', 
        'go_to_black_cube': 'go to the black cube', 
        'go_avoid_silver_ball': 'go to the silver ball and avoid the obstacle', 
        'go_to_cyan_ball': 'go to the cyan ball', 
        'go_avoid_pink_cube': 'go to the pink cube and avoid the obstacle', 
        'go_to_green_cube': 'go to the green cube', 
        'go_to_silver_cube': 'go to the silver cube', 
        'go_avoid_black_cube': 'go to the black cube and avoid the obstacle', 
        'go_to_blue_ball': 'go to the blue ball', 
        'go_avoid_blue_ball': 'go to the blue ball and avoid the obstacle', 
        'go_to_gold_ball': 'go to the gold ball', 
},
    '0206_test': 
    {
        'go_to_texture_vase': 'go to the vase', 
        # 'go_to_orange_ball': 'go to the orange ball', 
        'go_to_texture_fan': 'go to the fan', 
        'go_to_texture_bookshelf': 'go to the bookshelf', 
        # 'go_avoid_texture_drawers': 'go to the drawers and avoid the obstacle', 
        # 'go_avoid_texture_fence': 'go to the fence and avoid the obstacle', 
        'go_to_texture_bench': 'go to the bench', 
        'go_avoid_texture_trashcan': 'go to the trashcan and avoid the obstacle', 
        'go_avoid_texture_bookshelf': 'go to the bookshelf and avoid the obstacle', 
        # 'go_avoid_texture_oven': 'go to the oven and avoid the obstacle',
        'go_avoid_red_cube': 'go to the red cube and avoid the obstacle', 
        # 'go_to_purple_cube': 'go to the purple cube', 
        # 'go_avoid_tan_ball': 'go to the tan ball and avoid the obstacle', 
        'go_to_texture_wardrobe': 'go to the wardrobe', 
        'go_avoid_texture_sofa': 'go to the sofa and avoid the obstacle',
        # 'go_avoid_orange_cube': 'go to the orange cube and avoid the obstacle', 
        'go_to_texture_cooker': 'go to the cooker', 
        # 'go_avoid_purple_ball': 'go to the purple ball and avoid the obstacle', 
        'go_to_texture_trashcan': 'go to the trashcan',
        'go_avoid_texture_wardrobe': 'go to the wardrobe and avoid the obstacle', 
        'go_avoid_texture_barrel': 'go to the barrel and avoid the obstacle', 
        'go_avoid_texture_fan': 'go to the fan and avoid the obstacle',
        'go_to_texture_fence': 'go to the fence', 
        'go_to_texture_piano': 'go to the piano', 
        'go_avoid_texture_table': 'go to the table and avoid the obstacle',
        'go_avoid_texture_piano': 'go to the piano and avoid the obstacle', 
        'go_avoid_texture_vase': 'go to the vase and avoid the obstacle', 
        'go_to_texture_drawers': 'go to the drawers', 
        'go_avoid_texture_cooker': 'go to the cooker and avoid the obstacle', 
        'go_to_texture_barrel': 'go to the barrel', 
        'go_to_texture_chair': 'go to the chair', 
        'go_to_texture_table': 'go to the table', 
        'go_avoid_texture_chair': 'go to the chair and avoid the obstacle', 
        'go_to_texture_sofa': 'go to the sofa', 
        'go_avoid_texture_bench': 'go to the bench and avoid the obstacle', 
        'go_to_texture_oven': 'go to the oven', 
        'go_avoid_green_ball': 'go to the green ball and avoid the obstacle', 
        'go_avoid_green_cube': 'go to the green cube and avoid the obstacle', 
        'go_avoid_blue_cube': 'go to the blue cube and avoid the obstacle', 
        # 'go_to_cyan_cube': 'go to the cyan cube', 
        # 'go_to_gold_cube': 'go to the gold cube', 
        # 'go_avoid_cyan_ball': 'go to the cyan ball and avoid the obstacle', 
        # 'go_through_pink_triangle tunnel': 'go through the pink triangle tunnel', 
        # 'go_avoid_pink_ball': 'go to the pink ball and avoid the obstacle', 
        # 'go_avoid_navy_ball': 'go to the navy ball and avoid obstacle',
        # 'go_to_silver_ball': 'go to the silver ball', 
        # 'go_to_black_ball': 'go to the black ball', 
        'go_to_red_cube': 'go to the red cube', 
        'go_avoid_black_ball': 'go to the black ball and avoid the obstacle', 
        'go_avoid_yellow_cube': 'go to the yellow cube and avoid the obstacle', 
        # 'go_to_white_cube': 'go to the white cube',
        # 'go_avoid_white_cube': 'go to the white cube and avoid the obstacle', 
        # 'go_avoid_cyan_cube': 'go to the cyan cube and avoid the obstacle', 
        # 'go_avoid_gray_cube': 'go to the gray cube and avoid the obstacle', 
        # 'go_avoid_purple_cube': 'go to the purple cube and avoid the obstacle', 
        # 'go_to_navy_ball': 'go to the navy ball', 
        # 'go_to_tan_cube': 'go to the tan cube', 
        # 'go_to_pink_ball': 'go to the pink ball', 
        # 'go_avoid_beige_ball': 'go to the beige ball and avoid the obstacle', 
        # 'go_to_black_cube': 'go to the black cube', 
        # 'go_avoid_silver_ball': 'go to the silver ball and avoid the obstacle', 
        # 'go_to_cyan_ball': 'go to the cyan ball', 
        # 'go_avoid_pink_cube': 'go to the pink cube and avoid the obstacle', 
        'go_to_green_cube': 'go to the green cube', 
        # 'go_to_silver_cube': 'go to the silver cube', 
        # 'go_avoid_black_cube': 'go to the black cube and avoid the obstacle', 
        'go_to_blue_ball': 'go to the blue ball', 
        'go_avoid_blue_ball': 'go to the blue ball and avoid the obstacle', 
        # 'go_to_gold_ball': 'go to the gold ball', 
},
    '0224_test': 
    {
        'go_to_texture_vase': 'go to the vase', 
        'go_to_texture_fan': 'go to the fan', 
        'go_to_texture_bookshelf': 'go to the bookshelf', 
        'go_to_texture_bench': 'go to the bench', 
        'go_to_texture_wardrobe': 'go to the wardrobe', 
        'go_to_texture_cooker': 'go to the cooker', 
        'go_to_texture_trashcan': 'go to the trashcan',
        'go_to_texture_fence': 'go to the fence', 
        'go_to_texture_piano': 'go to the piano', 
        'go_to_texture_drawers': 'go to the drawers', 
        'go_to_texture_barrel': 'go to the barrel', 
        'go_to_texture_chair': 'go to the chair', 
        'go_to_texture_table': 'go to the table', 
        'go_to_texture_sofa': 'go to the sofa', 
        'go_to_texture_oven': 'go to the oven',  
        'go_to_red_cube': 'go to the red cube', 
        'go_to_green_cube': 'go to the green cube', 
        'go_to_blue_ball': 'go to the blue ball', 
},

    'Full' :
{
        'go_to_texture_vase': 'go to the vase', 
        'go_to_texture_fan': 'go to the fan', 
        'go_to_texture_bookshelf': 'go to the bookshelf', 
        'go_to_texture_bench': 'go to the bench', 
        'go_to_texture_wardrobe': 'go to the wardrobe', 
        'go_to_texture_cooker': 'go to the cooker', 
        'go_to_texture_trashcan': 'go to the trashcan',
        'go_to_texture_fence': 'go to the fence', 
        'go_to_texture_piano': 'go to the piano', 
        'go_to_texture_barrel': 'go to the barrel', 
        'go_to_texture_chair': 'go to the chair', 
        'go_to_texture_table': 'go to the table', 
        'go_to_texture_drawers': 'go to the drawers', 
        'go_to_texture_sofa': 'go to the sofa', 
        'go_to_texture_oven': 'go to the oven', 
        
        'go_to_green_cube': 'go to the green cube', 
        'go_to_blue_ball': 'go to the blue ball', 
        'go_to_red_cube': 'go to the red cube', 

        'stop_yellow_ball': 'stop the yellow ball', 
        'stop_green_ball': 'stop the green ball', 
        'stop_blue_ball': 'stop the blue ball', 
        'stop_red_ball': 'stop the red ball', 
        
        'crawl_red_gate3': 'crawl under the bar', 
        'crawl_red_gate1': 'crawl under the bar', 
        'crawl_red_gate2': 'crawl under the bar', 
        
        'go_avoid_texture_wardrobe': 'go to the wardrobe and avoid the obstacle', 
        'go_avoid_texture_barrel': 'go to the barrel and avoid the obstacle', 
        'go_avoid_texture_fan': 'go to the fan and avoid the obstacle',
        'go_avoid_texture_table': 'go to the table and avoid the obstacle',
        'go_avoid_texture_piano': 'go to the piano and avoid the obstacle', 
        'go_avoid_texture_vase': 'go to the vase and avoid the obstacle', 
        'go_avoid_texture_cooker': 'go to the cooker and avoid the obstacle', 
        'go_avoid_texture_chair': 'go to the chair and avoid the obstacle', 
        'go_avoid_texture_bench': 'go to the bench and avoid the obstacle', 
        'go_avoid_texture_drawers': 'go to the drawers and avoid the obstacle', 
        'go_avoid_texture_fence': 'go to the fence and avoid the obstacle', 
        'go_avoid_texture_trashcan': 'go to the trashcan and avoid the obstacle', 
        'go_avoid_texture_bookshelf': 'go to the bookshelf and avoid the obstacle', 
        'go_avoid_texture_oven': 'go to the oven and avoid the obstacle',
        'go_avoid_texture_sofa': 'go to the sofa and avoid the obstacle',
        
        'go_avoid_red_cube': 'go to the red cube and avoid the obstacle', 
        'go_avoid_yellow_cube': 'go to the yellow cube and avoid the obstacle', 
        'go_avoid_green_cube': 'go to the green cube and avoid the obstacle', 
        'go_avoid_green_ball': 'go to the green ball and avoid the obstacle', 
        'go_avoid_blue_cube': 'go to the blue cube and avoid the obstacle', 
        'go_avoid_blue_ball': 'go to the blue ball and avoid the obstacle', 
        
        'go_through_green_rectangle tunnel': 'go through the green rectangle tunnel', 
        'go_through_green_triangle tunnel': 'go through the green triangle tunnel', 
        'go_through_red_rectangle tunnel': 'go through the red rectangle tunnel', 
        'go_through_red_triangle tunnel': 'go through the red triangle tunnel', 
        'go_through_yellow_triangle tunnel': 'go through the yellow triangle tunnel', 
        'go_through_yellow_rectangle tunnel': 'go through the yellow rectangle tunnel', 
        
        'distinguish_texture_a': 'distinguish letter a', 
        'distinguish_texture_b': 'distinguish letter b',
        'distinguish_texture_c': 'distinguish letter c', 
        'distinguish_texture_d': 'distinguish letter d', 
        'distinguish_texture_e': 'distinguish letter e', 
        
        'unload_red_traybox': 'unload the ball into the red traybox', 
        'unload_green_traybox': 'unload the ball into the green traybox', 
        'unload_yellow_traybox': 'unload the ball into the yellow traybox', 
        'unload_blue_traybox': 'unload the ball into the blue traybox', 
        
        
    },
        'Full_seen' :
{
        'go_to_texture_vase': 'go to the vase', 
        'go_avoid_texture_vase': 'go to the vase and avoid the obstacle',

        'go_avoid_texture_fan': 'go to the fan and avoid the obstacle',
        'go_to_texture_fan': 'go to the fan', 

        # 'go_to_texture_bookshelf': 'go to the bookshelf', 
        # 'go_avoid_texture_bookshelf': 'go to the bookshelf and avoid the obstacle', 

        'go_avoid_texture_drawers': 'go to the drawers and avoid the obstacle', 
        'go_to_texture_drawers': 'go to the drawers', 

        'go_to_texture_fence': 'go to the fence', 
        'go_avoid_texture_fence': 'go to the fence and avoid the obstacle', 

        # 'go_avoid_texture_bench': 'go to the bench and avoid the obstacle', 
        # 'go_to_texture_bench': 'go to the bench', 

        # 'go_avoid_texture_trashcan': 'go to the trashcan and avoid the obstacle', 
        # 'go_to_texture_trashcan': 'go to the trashcan',

        'stop_yellow_ball': 'stop the yellow ball', 
        'stop_red_ball': 'stop the red ball',
        'stop_blue_ball': 'stop the blue ball', 
        'stop_green_ball': 'stop the green ball', 
        'go_avoid_green_ball': 'go to the green ball and avoid the obstacle',
        'go_to_blue_ball': 'go to the blue ball', 
        'go_avoid_blue_ball': 'go to the blue ball and avoid the obstacle',  

        'unload_red_traybox': 'unload the ball into the red traybox', 
        'unload_yellow_traybox': 'unload the ball into the yellow traybox', 
        'unload_blue_traybox': 'unload the ball into the blue traybox', 
        'unload_green_traybox': 'unload the ball into the green traybox', 

        # 'go_avoid_texture_oven': 'go to the oven and avoid the obstacle',
        # 'go_to_texture_oven': 'go to the oven', 

        'go_avoid_red_cube': 'go to the red cube and avoid the obstacle', 
        'go_avoid_green_cube': 'go to the green cube and avoid the obstacle', 
        'go_avoid_blue_cube': 'go to the blue cube and avoid the obstacle', 
        'go_to_red_cube': 'go to the red cube', 
        'go_avoid_yellow_cube': 'go to the yellow cube and avoid the obstacle', 
        'go_to_green_cube': 'go to the green cube', 

        'go_to_texture_wardrobe': 'go to the wardrobe', 
        'go_avoid_texture_wardrobe': 'go to the wardrobe and avoid the obstacle',

        'go_avoid_texture_sofa': 'go to the sofa and avoid the obstacle',
        'go_to_texture_sofa': 'go to the sofa', 

        'go_to_texture_cooker': 'go to the cooker', 
        'go_avoid_texture_cooker': 'go to the cooker and avoid the obstacle', 

        # 'go_avoid_texture_barrel': 'go to the barrel and avoid the obstacle', 
        # 'go_to_texture_barrel': 'go to the barrel', 

        'go_to_texture_piano': 'go to the piano', 
        'go_avoid_texture_piano': 'go to the piano and avoid the obstacle', 

        'go_avoid_texture_table': 'go to the table and avoid the obstacle',
        'go_to_texture_table': 'go to the table', 

        'crawl_red_gate3': 'crawl under the bar', 
        'crawl_red_gate2': 'crawl under the bar', 
        'crawl_red_gate1': 'crawl under the bar', 

        'go_to_texture_chair': 'go to the chair', 
        'go_avoid_texture_chair': 'go to the chair and avoid the obstacle', 

        'distinguish_texture_c': 'distinguish letter c', 
        # 'distinguish_texture_d': 'distinguish letter d',
        'distinguish_texture_b': 'distinguish letter b',
        'distinguish_texture_a': 'distinguish letter a', 
        # 'distinguish_texture_e': 'distinguish letter e',  

        'go_through_green_rectangle tunnel': 'go through the green rectangle tunnel', 
        'go_through_red_rectangle tunnel': 'go through the red rectangle tunnel', 
        'go_through_red_triangle tunnel': 'go through the red triangle tunnel', 
        'go_through_yellow_triangle tunnel': 'go through the yellow triangle tunnel', 
        'go_through_green_triangle tunnel': 'go through the green triangle tunnel', 
        'go_through_yellow_rectangle tunnel': 'go through the yellow rectangle tunnel', 



    }

}

REAL_INSTRUCTION_DICT = {
    '1228_test':
    {
        'find_yellow_ball': 'go to the yellow ball',
    },
    '0116_test': 
    {
        'find_square': 'go to the square sign',
        # 'find_yellow_ball': 'go to the yellow ball',
        'find_triangle': 'go to the triangle sign',
        'find_a': 'go to the letter a',
        'find_b': 'go to the letter c',
        'find_blue_ball': 'go to the blue ball',
        'find_blue':'go to the blue ball',
        'find_c':'go to the letter c',
        'find_circle':'go to the circle sign',
        'find_red_ball': 'go to the red ball',
    } ,
    '0206_test': 
    {
        # 'find_square': 'go to the square sign',
        'find_yellow_ball': 'go to the yellow ball',
        # 'find_triangle': 'go to the triangle sign',
        # 'find_a': 'go to the letter a',
        # 'find_b': 'go to the letter c',
        'find_blue_ball': 'go to the blue ball',
        # 'find_blue':'go to the blue ball',
        # 'find_c':'go to the letter c',
        # 'find_circle':'go to the circle sign',
        'find_red_ball': 'go to the red ball',
    },    
    '0224_test': 
    {
        'find_yellow_ball': 'go to the yellow ball',
        'find_blue_ball': 'go to the blue ball',
        'find_red_ball': 'go to the red ball',
    },
    'Full': 
    {
        'find_yellow_ball': 'go to the yellow ball',
        'find_blue_ball': 'go to the blue ball',
        'find_red_ball': 'go to the red ball',
    } ,
    'Full_seen': 
    {
        'find_yellow_ball': 'go to the yellow ball',
        'find_blue_ball': 'go to the blue ball',
        'find_red_ball': 'go to the red ball',
    } ,
                        
} 


